version: '2'
services:
    foodbuddy-app:
        image: foodbuddy
        environment:
            - SPRING_PROFILES_ACTIVE=prod,swagger
            - SPRING_DATA_MONGODB_URI=mongodb://foodbuddy-mongodb:27017
            - SPRING_DATA_MONGODB_DATABASE=FoodBuddy
            - JHIPSTER_SLEEP=10 # gives time for the database to boot before the application
        ports:
            - 8080:8080
    foodbuddy-mongodb:
        extends:
            file: mongodb.yml
            service: foodbuddy-mongodb
